language: node_js
sudo: false
node_js:
  - "iojs"
  - "7"
install:
  - npm install minifier
script:
  - minify --output $TRAVIS_BUILD_DIR/release/mapFactory.min.js $TRAVIS_BUILD_DIR/src/mapFactory.js 
