language: node_js
sudo: false
node_js:
  - "7"
install:
  - npm install uglify-js -g
script:
  - uglifyjs $TRAVIS_BUILD_DIR/src/mapFactory.js --compress --output $TRAVIS_BUILD_DIR/release/mapFactory.min.js  
